# Generated by Django 4.2.5 on 2023-10-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.TextField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
