# Generated by Django 4.2.5 on 2023-10-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_studentprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='has_graduated',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='has_paid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
