# Generated by Django 4.2.5 on 2023-10-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_teacher_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('S', 'Student'), ('T', 'Teacher')], max_length=1, null=True),
        ),
    ]
