# Generated by Django 4.2.5 on 2023-11-05 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_course_classroom'),
        ('users', '0014_alter_classroom_student_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classroom',
        ),
    ]
