# Generated by Django 4.2.5 on 2023-11-27 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_course_price'),
        ('users', '0018_alter_studentprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBuying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('full', 'Full'), ('subscription', 'Subscription')], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile')),
            ],
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='courses',
            field=models.ManyToManyField(related_name='students_bought', through='users.CourseBuying', to='courses.course'),
        ),
    ]
