# Generated by Django 4.2.5 on 2023-12-04 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_coursebuying_studentprofile_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursebuying',
            name='payment_type',
        ),
    ]
