# Generated by Django 4.2.5 on 2023-12-07 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_coursebuying_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='has_paid',
        ),
    ]
