# Generated by Django 4.2.5 on 2024-02-08 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0016_remove_course_classroom"),
        ("users", "0023_remove_studentprofile_joined_classroom"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoursePassing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("passed", models.BooleanField(default=False)),
                ("score", models.PositiveIntegerField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.course"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.studentprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="courses_passed",
            field=models.ManyToManyField(
                null=True,
                related_name="students_passed",
                through="users.CoursePassing",
                to="courses.course",
            ),
        ),
    ]
