# Generated by Django 4.2.5 on 2024-04-02 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("classroom", "0011_alter_classroom_course"),
        ("users", "0025_alter_studentprofile_courses_passed"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="classroom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrolled_students",
                to="classroom.classroom",
            ),
        ),
    ]
