# Generated by Django 4.2.5 on 2024-01-12 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quizes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=250)),
                ("choice_a", models.CharField(max_length=150)),
                ("choice_b", models.CharField(max_length=150)),
                ("choice_c", models.CharField(max_length=150)),
                ("choice_d", models.CharField(max_length=150)),
                (
                    "correct_answer",
                    models.CharField(
                        choices=[
                            ("A", "Choice A"),
                            ("B", "Choice B"),
                            ("C", "Choice C"),
                            ("D", "Choice D"),
                        ],
                        max_length=1,
                        verbose_name="correct_answer",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="quizes.quiz",
                    ),
                ),
            ],
        ),
    ]
