# Generated by Django 4.2.5 on 2024-01-14 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0015_course_price"),
        ("quizes", "0002_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="module",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz",
                to="courses.module",
            ),
        ),
    ]
