# Generated by Django 4.2.5 on 2024-01-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizes", "0003_alter_quiz_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quiz",
            name="close_date",
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name="quiz",
            name="open_date",
            field=models.DateTimeField(default=None),
        ),
    ]
