# Generated by Django 4.2.5 on 2024-03-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizes", "0011_alter_quizresults_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="final",
            field=models.BooleanField(default=False),
        ),
    ]
