# Generated by Django 4.2.5 on 2023-10-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_classroom'),
        ('courses', '0004_alter_course_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.AddField(
            model_name='course',
            name='classroom',
            field=models.ManyToManyField(blank=True, related_name='courses', to='users.classroom'),
        ),
    ]
