# Generated by Django 4.2.5 on 2023-10-22 20:45

import courses.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_course_students_course_classroom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='course',
            name='order',
            field=courses.fields.CustomPositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=courses.fields.CustomPositiveIntegerField(null=True),
        ),
    ]
