# Generated by Django 4.2.5 on 2023-10-27 18:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0007_videoitem_textitem_image_fileitem_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileItem',
            new_name='File',
        ),
        migrations.RenameModel(
            old_name='TextItem',
            new_name='Text',
        ),
        migrations.RenameModel(
            old_name='VideoItem',
            new_name='Video',
        ),
    ]
