# Generated by Django 4.2.5 on 2023-10-27 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_classroom_student_count'),
        ('courses', '0008_rename_fileitem_file_rename_textitem_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_related', to='users.teacher'),
        ),
        migrations.AlterField(
            model_name='image',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_related', to='users.teacher'),
        ),
        migrations.AlterField(
            model_name='text',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_related', to='users.teacher'),
        ),
        migrations.AlterField(
            model_name='video',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_related', to='users.teacher'),
        ),
    ]
