# Generated by Django 4.2.5 on 2023-10-28 18:05

import courses.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_content_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='order',
            field=courses.fields.CustomPositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
