# Generated by Django 4.2.5 on 2023-11-02 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_prerequisites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.RemoveField(
            model_name='course',
            name='order',
        ),
    ]
