# Generated by Django 4.2.5 on 2023-11-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        ('courses', '0013_alter_course_options_remove_course_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='classroom',
            field=models.ManyToManyField(blank=True, related_name='courses', to='classroom.classroom'),
        ),
    ]
