# Generated by Django 4.2.5 on 2024-01-23 19:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0015_course_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="classroom",
        ),
    ]
