# Generated by Django 4.2.5 on 2023-11-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_delete_classroom'),
        ('classroom', '0002_alter_classroom_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(related_name='joined_class', to='users.studentprofile'),
        ),
    ]
