# Generated by Django 4.2.5 on 2023-11-15 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_alter_classroom_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 14, 4, 53, 132200, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 14, 4, 53, 132200, tzinfo=datetime.timezone.utc)),
        ),
    ]
