# Generated by Django 4.2.5 on 2023-11-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_alter_classroom_end_date_alter_classroom_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='title',
            field=models.CharField(max_length=50, unique_for_date=True),
        ),
    ]
