# Generated by Django 4.2.5 on 2023-11-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_alter_classroom_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
