# Generated by Django 4.2.5 on 2024-01-23 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0016_remove_course_classroom"),
        ("classroom", "0009_remove_classroom_course_classroom_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.course",
            ),
        ),
    ]
