# Generated by Django 4.2.5 on 2024-02-01 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0016_remove_course_classroom"),
        ("classroom", "0010_classroom_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classrooms",
                to="courses.course",
            ),
        ),
    ]
